name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ 62440afea38b3c3684e5b74ba283016e }}
          TIMEZONE: Asia/Seoul
